export interface DialCode {
  name: string;
  code: string;
  dial: string;
  flag: string;
}

export const DIAL_CODES: DialCode[] = [
  { name: "Afghanistan", code: "AF", dial: "+93", flag: "🇦🇫" },
  { name: "Albanie", code: "AL", dial: "+355", flag: "🇦🇱" },
  { name: "Algérie", code: "DZ", dial: "+213", flag: "🇩🇿" },
  { name: "Allemagne", code: "DE", dial: "+49", flag: "🇩🇪" },
  { name: "Andorre", code: "AD", dial: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "AO", dial: "+244", flag: "🇦🇴" },
  { name: "Arabie Saoudite", code: "SA", dial: "+966", flag: "🇸🇦" },
  { name: "Argentine", code: "AR", dial: "+54", flag: "🇦🇷" },
  { name: "Arménie", code: "AM", dial: "+374", flag: "🇦🇲" },
  { name: "Australie", code: "AU", dial: "+61", flag: "🇦🇺" },
  { name: "Autriche", code: "AT", dial: "+43", flag: "🇦🇹" },
  { name: "Azerbaïdjan", code: "AZ", dial: "+994", flag: "🇦🇿" },
  { name: "Bahamas", code: "BS", dial: "+1-242", flag: "🇧🇸" },
  { name: "Bangladesh", code: "BD", dial: "+880", flag: "🇧🇩" },
  { name: "Belgique", code: "BE", dial: "+32", flag: "🇧🇪" },
  { name: "Bénin", code: "BJ", dial: "+229", flag: "🇧🇯" },
  { name: "Bolivie", code: "BO", dial: "+591", flag: "🇧🇴" },
  { name: "Bosnie-Herzégovine", code: "BA", dial: "+387", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", dial: "+267", flag: "🇧🇼" },
  { name: "Brésil", code: "BR", dial: "+55", flag: "🇧🇷" },
  { name: "Bulgarie", code: "BG", dial: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", dial: "+226", flag: "🇧🇫" },
  { name: "Burundi", code: "BI", dial: "+257", flag: "🇧🇮" },
  { name: "Cambodge", code: "KH", dial: "+855", flag: "🇰🇭" },
  { name: "Cameroun", code: "CM", dial: "+237", flag: "🇨🇲" },
  { name: "Canada", code: "CA", dial: "+1", flag: "🇨🇦" },
  { name: "Cap-Vert", code: "CV", dial: "+238", flag: "🇨🇻" },
  { name: "Chili", code: "CL", dial: "+56", flag: "🇨🇱" },
  { name: "Chine", code: "CN", dial: "+86", flag: "🇨🇳" },
  { name: "Chypre", code: "CY", dial: "+357", flag: "🇨🇾" },
  { name: "Colombie", code: "CO", dial: "+57", flag: "🇨🇴" },
  { name: "Comores", code: "KM", dial: "+269", flag: "🇰🇲" },
  { name: "Congo", code: "CG", dial: "+242", flag: "🇨🇬" },
  { name: "Congo (RDC)", code: "CD", dial: "+243", flag: "🇨🇩" },
  { name: "Corée du Sud", code: "KR", dial: "+82", flag: "🇰🇷" },
  { name: "Corée du Nord", code: "KP", dial: "+850", flag: "🇰🇵" },
  { name: "Costa Rica", code: "CR", dial: "+506", flag: "🇨🇷" },
  { name: "Côte d'Ivoire", code: "CI", dial: "+225", flag: "🇨🇮" },
  { name: "Croatie", code: "HR", dial: "+385", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", dial: "+53", flag: "🇨🇺" },
  { name: "Danemark", code: "DK", dial: "+45", flag: "🇩🇰" },
  { name: "Djibouti", code: "DJ", dial: "+253", flag: "🇩🇯" },
  { name: "Égypte", code: "EG", dial: "+20", flag: "🇪🇬" },
  { name: "Émirats arabes unis", code: "AE", dial: "+971", flag: "🇦🇪" },
  { name: "Équateur", code: "EC", dial: "+593", flag: "🇪🇨" },
  { name: "Érythrée", code: "ER", dial: "+291", flag: "🇪🇷" },
  { name: "Espagne", code: "ES", dial: "+34", flag: "🇪🇸" },
  { name: "Estonie", code: "EE", dial: "+372", flag: "🇪🇪" },
  { name: "Éthiopie", code: "ET", dial: "+251", flag: "🇪🇹" },
  { name: "Finlande", code: "FI", dial: "+358", flag: "🇫🇮" },
  { name: "France", code: "FR", dial: "+33", flag: "🇫🇷" },
  { name: "Gabon", code: "GA", dial: "+241", flag: "🇬🇦" },
  { name: "Gambie", code: "GM", dial: "+220", flag: "🇬🇲" },
  { name: "Géorgie", code: "GE", dial: "+995", flag: "🇬🇪" },
  { name: "Ghana", code: "GH", dial: "+233", flag: "🇬🇭" },
  { name: "Grèce", code: "GR", dial: "+30", flag: "🇬🇷" },
  { name: "Guatemala", code: "GT", dial: "+502", flag: "🇬🇹" },
  { name: "Guinée", code: "GN", dial: "+224", flag: "🇬🇳" },
  { name: "Guinée-Bissau", code: "GW", dial: "+245", flag: "🇬🇼" },
  { name: "Guinée équatoriale", code: "GQ", dial: "+240", flag: "🇬🇶" },
  { name: "Haïti", code: "HT", dial: "+509", flag: "🇭🇹" },
  { name: "Honduras", code: "HN", dial: "+504", flag: "🇭🇳" },
  { name: "Hongrie", code: "HU", dial: "+36", flag: "🇭🇺" },
  { name: "Inde", code: "IN", dial: "+91", flag: "🇮🇳" },
  { name: "Indonésie", code: "ID", dial: "+62", flag: "🇮🇩" },
  { name: "Irak", code: "IQ", dial: "+964", flag: "🇮🇶" },
  { name: "Iran", code: "IR", dial: "+98", flag: "🇮🇷" },
  { name: "Irlande", code: "IE", dial: "+353", flag: "🇮🇪" },
  { name: "Islande", code: "IS", dial: "+354", flag: "🇮🇸" },
  { name: "Israël", code: "IL", dial: "+972", flag: "🇮🇱" },
  { name: "Italie", code: "IT", dial: "+39", flag: "🇮🇹" },
  { name: "Jamaïque", code: "JM", dial: "+1-876", flag: "🇯🇲" },
  { name: "Japon", code: "JP", dial: "+81", flag: "🇯🇵" },
  { name: "Jordanie", code: "JO", dial: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", dial: "+7", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", dial: "+254", flag: "🇰🇪" },
  { name: "Kosovo", code: "XK", dial: "+383", flag: "🇽🇰" },
  { name: "Koweït", code: "KW", dial: "+965", flag: "🇰🇼" },
  { name: "Laos", code: "LA", dial: "+856", flag: "🇱🇦" },
  { name: "Lesotho", code: "LS", dial: "+266", flag: "🇱🇸" },
  { name: "Lettonie", code: "LV", dial: "+371", flag: "🇱🇻" },
  { name: "Liban", code: "LB", dial: "+961", flag: "🇱🇧" },
  { name: "Libéria", code: "LR", dial: "+231", flag: "🇱🇷" },
  { name: "Libye", code: "LY", dial: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "LI", dial: "+423", flag: "🇱🇮" },
  { name: "Lituanie", code: "LT", dial: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", dial: "+352", flag: "🇱🇺" },
  { name: "Madagascar", code: "MG", dial: "+261", flag: "🇲🇬" },
  { name: "Malaisie", code: "MY", dial: "+60", flag: "🇲🇾" },
  { name: "Malawi", code: "MW", dial: "+265", flag: "🇲🇼" },
  { name: "Mali", code: "ML", dial: "+223", flag: "🇲🇱" },
  { name: "Malte", code: "MT", dial: "+356", flag: "🇲🇹" },
  { name: "Maroc", code: "MA", dial: "+212", flag: "🇲🇦" },
  { name: "Martinique", code: "MQ", dial: "+596", flag: "🇲🇶" },
  { name: "Mauritanie", code: "MR", dial: "+222", flag: "🇲🇷" },
  { name: "Mexique", code: "MX", dial: "+52", flag: "🇲🇽" },
  { name: "Moldavie", code: "MD", dial: "+373", flag: "🇲🇩" },
  { name: "Monaco", code: "MC", dial: "+377", flag: "🇲🇨" },
  { name: "Mongolie", code: "MN", dial: "+976", flag: "🇲🇳" },
  { name: "Monténégro", code: "ME", dial: "+382", flag: "🇲🇪" },
  { name: "Mozambique", code: "MZ", dial: "+258", flag: "🇲🇿" },
  { name: "Namibie", code: "NA", dial: "+264", flag: "🇳🇦" },
  { name: "Népal", code: "NP", dial: "+977", flag: "🇳🇵" },
  { name: "Nicaragua", code: "NI", dial: "+505", flag: "🇳🇮" },
  { name: "Niger", code: "NE", dial: "+227", flag: "🇳🇪" },
  { name: "Nigéria", code: "NG", dial: "+234", flag: "🇳🇬" },
  { name: "Norvège", code: "NO", dial: "+47", flag: "🇳🇴" },
  { name: "Nouvelle-Zélande", code: "NZ", dial: "+64", flag: "🇳🇿" },
  { name: "Oman", code: "OM", dial: "+968", flag: "🇴🇲" },
  { name: "Ouganda", code: "UG", dial: "+256", flag: "🇺🇬" },
  { name: "Ouzbékistan", code: "UZ", dial: "+998", flag: "🇺🇿" },
  { name: "Pakistan", code: "PK", dial: "+92", flag: "🇵🇰" },
  { name: "Panama", code: "PA", dial: "+507", flag: "🇵🇦" },
  { name: "Paraguay", code: "PY", dial: "+595", flag: "🇵🇾" },
  { name: "Pays-Bas", code: "NL", dial: "+31", flag: "🇳🇱" },
  { name: "Pérou", code: "PE", dial: "+51", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", dial: "+63", flag: "🇵🇭" },
  { name: "Pologne", code: "PL", dial: "+48", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", dial: "+351", flag: "🇵🇹" },
  { name: "Qatar", code: "QA", dial: "+974", flag: "🇶🇦" },
  { name: "République dominicaine", code: "DO", dial: "+1-809", flag: "🇩🇴" },
  { name: "République tchèque", code: "CZ", dial: "+420", flag: "🇨🇿" },
  { name: "Réunion", code: "RE", dial: "+262", flag: "🇷🇪" },
  { name: "Roumanie", code: "RO", dial: "+40", flag: "🇷🇴" },
  { name: "Royaume-Uni", code: "GB", dial: "+44", flag: "🇬🇧" },
  { name: "Russie", code: "RU", dial: "+7", flag: "🇷🇺" },
  { name: "Rwanda", code: "RW", dial: "+250", flag: "🇷🇼" },
  { name: "Sénégal", code: "SN", dial: "+221", flag: "🇸🇳" },
  { name: "Serbie", code: "RS", dial: "+381", flag: "🇷🇸" },
  { name: "Sierra Leone", code: "SL", dial: "+232", flag: "🇸🇱" },
  { name: "Singapour", code: "SG", dial: "+65", flag: "🇸🇬" },
  { name: "Slovaquie", code: "SK", dial: "+421", flag: "🇸🇰" },
  { name: "Slovénie", code: "SI", dial: "+386", flag: "🇸🇮" },
  { name: "Somalie", code: "SO", dial: "+252", flag: "🇸🇴" },
  { name: "Soudan", code: "SD", dial: "+249", flag: "🇸🇩" },
  { name: "Sri Lanka", code: "LK", dial: "+94", flag: "🇱🇰" },
  { name: "Suède", code: "SE", dial: "+46", flag: "🇸🇪" },
  { name: "Suisse", code: "CH", dial: "+41", flag: "🇨🇭" },
  { name: "Suriname", code: "SR", dial: "+597", flag: "🇸🇷" },
  { name: "Syrie", code: "SY", dial: "+963", flag: "🇸🇾" },
  { name: "Tadjikistan", code: "TJ", dial: "+992", flag: "🇹🇯" },
  { name: "Tanzanie", code: "TZ", dial: "+255", flag: "🇹🇿" },
  { name: "Tchad", code: "TD", dial: "+235", flag: "🇹🇩" },
  { name: "Thaïlande", code: "TH", dial: "+66", flag: "🇹🇭" },
  { name: "Togo", code: "TG", dial: "+228", flag: "🇹🇬" },
  { name: "Tunisie", code: "TN", dial: "+216", flag: "🇹🇳" },
  { name: "Turkménistan", code: "TM", dial: "+993", flag: "🇹🇲" },
  { name: "Turquie", code: "TR", dial: "+90", flag: "🇹🇷" },
  { name: "Ukraine", code: "UA", dial: "+380", flag: "🇺🇦" },
  { name: "Uruguay", code: "UY", dial: "+598", flag: "🇺🇾" },
  { name: "États-Unis", code: "US", dial: "+1", flag: "🇺🇸" },
  { name: "Venezuela", code: "VE", dial: "+58", flag: "🇻🇪" },
  { name: "Vietnam", code: "VN", dial: "+84", flag: "🇻🇳" },
  { name: "Yémen", code: "YE", dial: "+967", flag: "🇾🇪" },
  { name: "Zambie", code: "ZM", dial: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", dial: "+263", flag: "🇿🇼" },
];

export const DEFAULT_DIAL = DIAL_CODES.find(d => d.code === "CA")!;

export function findDialByPhone(phone: string): DialCode | undefined {
  const normalized = phone.replace(/\s/g, "");
  let best: DialCode | undefined;
  let bestLen = 0;
  for (const d of DIAL_CODES) {
    const raw = d.dial.replace(/-.*/, "");
    if (normalized.startsWith(raw) && raw.length > bestLen) {
      best = d;
      bestLen = raw.length;
    }
  }
  return best;
}
